### ISSUE TITLE
What is the purpose of empty.cpp?

### ISSUE THREAD

**Issue by HTRamsey** [mavlink/libevents#11]
It just causes a warning to be generated by cmake

**Comment by bkueng** [comment]
I remember having to add it because cmake would not allow for a library w/o source files. But if it warns now there's probably a better way.
What is the warning?

**Comment by HTRamsey** [comment]
Extremely minor warning and not a big, was just curious.
![image](https://github.com/user-attachments/assets/466ca70a-a8e1-46d1-9025-684485c8d875)
I can just add SKIP_AUTOGEN and point to that file.

**Comment by bkueng** [comment]
This should be better: https://github.com/mavlink/libevents/pull/12
Can you give it a try?

**Comment by HTRamsey** [comment]
Yup that seems to work
